/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardRepositoriesRouteImport } from './routes/_authenticated/dashboard/repositories'
import { Route as AuthenticatedDashboardActionsRouteImport } from './routes/_authenticated/dashboard/actions'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin.organizations'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedDashboardSettingsSecretsRouteImport } from './routes/_authenticated/dashboard/settings/secrets'
import { Route as AuthenticatedDashboardSettingsKeysRouteImport } from './routes/_authenticated/dashboard/settings/keys'
import { Route as AuthenticatedDashboardSettingsIntegrationsRouteImport } from './routes/_authenticated/dashboard/settings/integrations'
import { Route as AuthenticatedDashboardSettingsApiKeysRouteImport } from './routes/_authenticated/dashboard/settings/api-keys'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRepositoriesRoute =
  AuthenticatedDashboardRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardActionsRoute =
  AuthenticatedDashboardActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardSettingsSecretsRoute =
  AuthenticatedDashboardSettingsSecretsRouteImport.update({
    id: '/settings/secrets',
    path: '/settings/secrets',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsKeysRoute =
  AuthenticatedDashboardSettingsKeysRouteImport.update({
    id: '/settings/keys',
    path: '/settings/keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsIntegrationsRoute =
  AuthenticatedDashboardSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsApiKeysRoute =
  AuthenticatedDashboardSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/dashboard/actions': typeof AuthenticatedDashboardActionsRoute
  '/dashboard/repositories': typeof AuthenticatedDashboardRepositoriesRoute
  '/dashboard/settings/api-keys': typeof AuthenticatedDashboardSettingsApiKeysRoute
  '/dashboard/settings/integrations': typeof AuthenticatedDashboardSettingsIntegrationsRoute
  '/dashboard/settings/keys': typeof AuthenticatedDashboardSettingsKeysRoute
  '/dashboard/settings/secrets': typeof AuthenticatedDashboardSettingsSecretsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/dashboard/actions': typeof AuthenticatedDashboardActionsRoute
  '/dashboard/repositories': typeof AuthenticatedDashboardRepositoriesRoute
  '/dashboard/settings/api-keys': typeof AuthenticatedDashboardSettingsApiKeysRoute
  '/dashboard/settings/integrations': typeof AuthenticatedDashboardSettingsIntegrationsRoute
  '/dashboard/settings/keys': typeof AuthenticatedDashboardSettingsKeysRoute
  '/dashboard/settings/secrets': typeof AuthenticatedDashboardSettingsSecretsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/dashboard/actions': typeof AuthenticatedDashboardActionsRoute
  '/_authenticated/dashboard/repositories': typeof AuthenticatedDashboardRepositoriesRoute
  '/_authenticated/dashboard/settings/api-keys': typeof AuthenticatedDashboardSettingsApiKeysRoute
  '/_authenticated/dashboard/settings/integrations': typeof AuthenticatedDashboardSettingsIntegrationsRoute
  '/_authenticated/dashboard/settings/keys': typeof AuthenticatedDashboardSettingsKeysRoute
  '/_authenticated/dashboard/settings/secrets': typeof AuthenticatedDashboardSettingsSecretsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/dashboard'
    | '/checkout/return'
    | '/admin/leads'
    | '/admin/organizations'
    | '/dashboard/actions'
    | '/dashboard/repositories'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/integrations'
    | '/dashboard/settings/keys'
    | '/dashboard/settings/secrets'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/dashboard'
    | '/checkout/return'
    | '/admin/leads'
    | '/admin/organizations'
    | '/dashboard/actions'
    | '/dashboard/repositories'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/integrations'
    | '/dashboard/settings/keys'
    | '/dashboard/settings/secrets'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/checkout/return'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/dashboard/actions'
    | '/_authenticated/dashboard/repositories'
    | '/_authenticated/dashboard/settings/api-keys'
    | '/_authenticated/dashboard/settings/integrations'
    | '/_authenticated/dashboard/settings/keys'
    | '/_authenticated/dashboard/settings/secrets'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/repositories': {
      id: '/_authenticated/dashboard/repositories'
      path: '/repositories'
      fullPath: '/dashboard/repositories'
      preLoaderRoute: typeof AuthenticatedDashboardRepositoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/actions': {
      id: '/_authenticated/dashboard/actions'
      path: '/actions'
      fullPath: '/dashboard/actions'
      preLoaderRoute: typeof AuthenticatedDashboardActionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings/secrets': {
      id: '/_authenticated/dashboard/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/dashboard/settings/secrets'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsSecretsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings/keys': {
      id: '/_authenticated/dashboard/settings/keys'
      path: '/settings/keys'
      fullPath: '/dashboard/settings/keys'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings/integrations': {
      id: '/_authenticated/dashboard/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/dashboard/settings/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings/api-keys': {
      id: '/_authenticated/dashboard/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/dashboard/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardActionsRoute: typeof AuthenticatedDashboardActionsRoute
  AuthenticatedDashboardRepositoriesRoute: typeof AuthenticatedDashboardRepositoriesRoute
  AuthenticatedDashboardSettingsApiKeysRoute: typeof AuthenticatedDashboardSettingsApiKeysRoute
  AuthenticatedDashboardSettingsIntegrationsRoute: typeof AuthenticatedDashboardSettingsIntegrationsRoute
  AuthenticatedDashboardSettingsKeysRoute: typeof AuthenticatedDashboardSettingsKeysRoute
  AuthenticatedDashboardSettingsSecretsRoute: typeof AuthenticatedDashboardSettingsSecretsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardActionsRoute: AuthenticatedDashboardActionsRoute,
    AuthenticatedDashboardRepositoriesRoute:
      AuthenticatedDashboardRepositoriesRoute,
    AuthenticatedDashboardSettingsApiKeysRoute:
      AuthenticatedDashboardSettingsApiKeysRoute,
    AuthenticatedDashboardSettingsIntegrationsRoute:
      AuthenticatedDashboardSettingsIntegrationsRoute,
    AuthenticatedDashboardSettingsKeysRoute:
      AuthenticatedDashboardSettingsKeysRoute,
    AuthenticatedDashboardSettingsSecretsRoute:
      AuthenticatedDashboardSettingsSecretsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
